pipeline {

    agent { label "scarf" }

/*

    tiggers {
        cron("* * * * 1")
    }

*/

    stages {

        stage("Notify") {
            steps {
                echo "Starting from SCARF"
            }
        }

    }
}