[tox]
min_version = 4.0
# The python environments to run the tests in
envlist = py{311,312,313,314,314}
allowlist_externals = git

[testenv]
package = wheel
changedir = tests_and_analysis/test
test_command = python run_tests.py --report
passenv = CC_LD
install_command =
    python -m pip install -v \
        --force-reinstall \
        --upgrade \
        --upgrade-strategy eager \
        {opts} \
        {packages}
dependency_groups =
    test

# Test with all extras
[testenv:py{311,312,313,314}]
platform = (linux)|(win32)
extras =
    matplotlib
    phonopy-reader
commands =
    {[testenv]test_command} {posargs} -m "not brille"
