[tox]
min_version = 4.0
# The python environments to run the tests in
envlist = py{311,312,313,314,315},py310-{base,brille,matplotlib,phonopy-reader,all,minrequirements,no-c}
labels =
    ci-base = py311,py312,py313,py314,py315,py310-base,py310-brille,py310-matplotlib,py310-phonopy-reader,py310-all,py310-minrequirements,py310-no-c
    ci-coverage = py314-cov,py312,py313,py314,py315,py310-base,py310-brille,py310-matplotlib,py310-phonopy-reader,py310-all,py310-minrequirements,py310-no-c,coverage-badge
    coverage-local = py314-cov,coverage-badge
allowlist_externals = git

[testenv]
package = wheel
changedir = tests_and_analysis/test
test_command = python run_tests.py --report
passenv = CC_LD
install_command =
    python -m pip install -v \
        --force-reinstall \
        --upgrade \
        --upgrade-strategy eager \
        {opts} \
        {packages}
dependency_groups =
    test
allowlist_externals = mkdir, mv

# Test with all extras.
# brille and non-brille tests are run as separate pytest invocations:
# importing brille often creates OpenMP conflicts, and Euphonic avoid deadlocks
# in this case by falling back to OMP_NUM_THREADS=1. By isolating most tests
# from this scenario they can still benefit from parallelism.
[testenv:py{311,312,313,314}]
extras =
    matplotlib
    phonopy-reader
    brille
commands =
    {[testenv]test_command} {posargs} -m "brille"
    {[testenv]test_command} {posargs} -m "not brille"

# Py3.15 is pre-release, test without extras
[testenv:py315]
commands = {[testenv]test_command} {posargs} -m "not (phonopy_reader or matplotlib or brille)"

# Test with no extras
[testenv:py310-base]
commands = {[testenv]test_command} {posargs} -m "not (phonopy_reader or matplotlib or brille)"

# Test with matplotlib extra only
[testenv:py310-matplotlib]
extras =
    matplotlib
commands = {[testenv]test_command} {posargs} -m "matplotlib and not multiple_extras"

# Test with phonopy-reader extra only
[testenv:py310-phonopy-reader]
extras =
    phonopy-reader
commands = {[testenv]test_command} {posargs} -m "phonopy_reader and not multiple_extras"

# Test with brille extra only
[testenv:py310-brille]
extras =
    brille
commands = {[testenv]test_command} {posargs} -m "brille and not multiple_extras"

# Run remaining tests that require multiple extras
[testenv:py310-all]
extras =
    matplotlib
    phonopy-reader
    brille
commands =
    {[testenv]test_command} {posargs} -m "multiple_extras"

# Test without building C extension
[testenv:py310-no-c]
platform = linux
install_command = {[testenv]install_command} -Csetup-args="-Dpython_only=true"
extras =
    matplotlib
    phonopy-reader
    brille
commands = {[testenv]test_command} {posargs} -m "not c_extension"

# Test with minimum supported dependency versions
[testenv:py310-minrequirements]
dependency_groups =
    {[testenv]dependency_groups}
    min_reqs
deps =
    numpy==1.24
    setuptools==60.*
extras =
    matplotlib
    phonopy-reader
    brille
commands =
    {[testenv]test_command} {posargs} -m "brille"
    {[testenv]test_command} {posargs} -m "not brille"

# Test environment with coverage enabled for py314
[testenv:py314-cov]
extras =
    matplotlib
    phonopy-reader
    brille
commands_pre =
    python -m coverage erase
commands =
    {[testenv]test_command} --cov {posargs} -m "brille"
    {[testenv]test_command} --cov {posargs} -m "not brille"
commands_post =
    # Prepare .coverage for combining (needs a different name!)
    python -c "import os; os.rename('.coverage', '.coverage.data')"
    # "Combine" from project root so site-packages paths map to relative euphonic/ paths
    python -c "import os, coverage; os.chdir('../..'); cov = coverage.Coverage(data_file='tests_and_analysis/test/.coverage'); cov.combine(data_paths=['tests_and_analysis/test/.coverage.data']); cov.save()"
    # Generate XML and HTML reports
    python -m coverage xml
    python -m coverage html -d reports/htmlcov
    python -c "import os; os.rename('coverage.xml', 'reports/coverage.xml')"

# Coverage reporting environment
[testenv:coverage-badge]
description = Generate SVG badge from coverage XML
depends = py314-cov
deps =
    genbadge[coverage]
skip_install = true
commands =
    mkdir -p reports
    genbadge coverage -i reports/coverage.xml -o reports/coverage-badge.svg
