name: Build and test sdist

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Target branch / tag / commit"
        required: true
        type: string
  workflow_call:
    inputs:
      ref:
        description: "Target branch / tag / commit"
        required: true
        type: string

jobs:
  build-sdist:
    name: Build sdist
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.ref }}
          fetch-depth: 0
          fetch-tags: true

      - name: Create source distribution
        shell: bash -l {0}
        run: |
          pipx run build --sdist .

      - name: Upload source dist as build artifact
        uses: actions/upload-artifact@v4
        with:
            name: python-source-distribution
            path: dist/
            if-no-files-found: error

  test-sdist:
    needs: build-sdist
    name: Test build from sdist on Windows
    runs-on: windows-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.11

      - name: Remove Strawberry ccache binary (It confuses the meson build)
        shell: powershell
        run: |
          if (Test-Path "C:\Strawberry\c\bin\ccache.exe") {
              Remove-Item "C:\Strawberry\c\bin\ccache.exe" -Force
          }

      - name: Download sdist
        uses: actions/download-artifact@v4
        with:
          path: dist/
          merge-multiple: true

      - name: List downloaded sdist
        run: |
          ls -R dist/

      - name: Update pip
        shell: bash -l {0}
        run: |
          python -m pip install --upgrade pip

      - name: Install from sdist
        shell: bash -l {0}
        run: python -m pip install $(find dist -name 'euphonic-*.tar.gz')[matplotlib,phonopy-reader,brille]

      - name: Checkout repository (for tests and test data)
        uses: actions/checkout@v6

      - name: Delete source (to ensure we are testing INSTALLED version)
        shell: bash -l {0}
        run: |
          python -m pip install --group test
          rm -rf euphonic

      - name: run tests
        shell: bash -l {0}
        run: python tests_and_analysis/test/run_tests.py --report
