name: Changelog updated

on:
  pull_request:
    types: [opened, reopened, labeled, synchronize]

jobs:
  check_log:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Get changes
        run: |
          set +e  # Don't immediately fail when bash sees exit 1
          git diff --exit-code "origin/${GITHUB_BASE_REF}" -- CHANGELOG.rst
          if [ $? -eq 1 ]; then
              exit 0
          fi
          # git-diff did not return 1; either no changes or another error encountered
          exit 1
