name: test-prerelease-python
on:
  push:
    branches:
      - '**master**'
      - '**release**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: 3.14
      TOX_ENV: py314
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensure tags are fetched for versioning
          fetch-tags: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          allow-prereleases: true

      - name: Install HDF5
        shell: bash -l {0}
        run: |
          sudo apt install libhdf5-dev

      - name: Update pip and install dependencies
        shell: bash -l {0}
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r tests_and_analysis/ci_requirements.txt

      - name: Run tests
        shell: bash -l {0}
        run: python -m tox -e ${{ env.TOX_ENV }}

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Unit test results ${{ inputs.os }} ${{ inputs.python-prerelease && 'pre-release python' || '' }}
          path: tests_and_analysis/test/reports/junit_report*.xml
